In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
%matplotlib inline 

In [ ]:
df = pd.read_csv("7-cyber_attack_data.csv")

In [4]:
df.head()

src_packet_rate  dst_packet_rate  avg_payload_size  connection_duration  \
0        -1.286132        -0.648334          1.044115            -0.469715   
1        -0.222224         2.083232          1.191114            -1.354527   
2        -0.431963         0.375745         -1.370334             0.819214   
3        -0.912633         0.986988         -0.690042             2.014628   
4        -0.367056         1.667892          0.879172             2.214276   

   tcp_flag_count  avg_interarrival_time  failed_login_attempts  \
0        0.789859              -0.083727              -1.647309   
1       -0.956992               1.696028              -1.070406   
2        0.345243               1.389447              -1.904130   
3       -0.442260               0.590347              -1.819353   
4        1.846338              -0.894047               1.543838   

   unusual_port_activity_score  session_entropy  avg_response_delay  \
0                    -1.316412         1.011910           -0.898063   
1                     0.981403        -1.628798            1.377594   
2                     1.292602         0.925545            0.232705   
3                     1.560938         0.823755            0.517762   
4                     0.931103        -1.015210            1.061845   

   attack_type  
0            2  
1            0  
2            0  
3            0  
4            1

In [5]:
df.columns

Index(['src_packet_rate', 'dst_packet_rate', 'avg_payload_size',
       'connection_duration', 'tcp_flag_count', 'avg_interarrival_time',
       'failed_login_attempts', 'unusual_port_activity_score',
       'session_entropy', 'avg_response_delay', 'attack_type'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   src_packet_rate              1000 non-null   float64
 1   dst_packet_rate              1000 non-null   float64
 2   avg_payload_size             1000 non-null   float64
 3   connection_duration          1000 non-null   float64
 4   tcp_flag_count               1000 non-null   float64
 5   avg_interarrival_time        1000 non-null   float64
 6   failed_login_attempts        1000 non-null   float64
 7   unusual_port_activity_score  1000 non-null   float64
 8   session_entropy              1000 non-null   float64
 9   avg_response_delay           1000 non-null   float64
 10  attack_type                  1000 non-null   int64  
dtypes: float64(10), int64(1)
memory usage: 86.1 KB


In [7]:
X = df.drop("attack_type", axis = 1)
y = df["attack_type"]

In [9]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state=15)

In [10]:
from sklearn.linear_model import LogisticRegression 
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [11]:
y_pred

array([2, 0, 0, 0, 2, 0, 1, 1, 2, 0, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0, 0,
       0, 1, 1, 1, 1, 2, 2, 2, 1, 0, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 0, 2,
       1, 1, 2, 0, 0, 0, 2, 0, 1, 2, 0, 2, 1, 2, 2, 1, 0, 0, 0, 2, 1, 2,
       1, 0, 2, 0, 2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 1, 0, 1, 2, 2, 0, 2, 2,
       1, 0, 1, 0, 0, 0, 1, 1, 2, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 0, 0, 1,
       2, 1, 2, 1, 0, 1, 2, 0, 0, 1, 0, 0, 2, 1, 0, 1, 0, 2, 2, 1, 0, 2,
       2, 2, 1, 2, 0, 2, 0, 2, 1, 0, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 1, 1,
       0, 0, 1, 1, 1, 2, 2, 0, 0, 2, 2, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 2,
       0, 2, 2, 0, 2, 1, 1, 1, 2, 1, 0, 1, 0, 1, 1, 2, 0, 2, 1, 2, 1, 0,
       1, 2, 0, 2, 1, 0, 1, 0, 2, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0,
       2, 0, 2, 1, 2, 1, 0, 0, 1, 1, 2, 1, 0, 2, 1, 0, 2, 1, 1, 2, 2, 1,
       1, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 0, 0, 1, 2, 1, 1, 2, 0,
       2, 0, 1, 0, 1, 2, 2, 1, 2, 2, 2, 2, 0, 2, 1, 0, 0, 0, 2, 1, 2, 2,
       2, 1, 0, 0, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2])

In [12]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [15]:
score = accuracy_score(y_test, y_pred)
print("score: ", score)
print(classification_report(y_test, y_pred))
print("confusion matrix: \n", confusion_matrix(y_test, y_pred))

score:  0.7866666666666666
              precision    recall  f1-score   support

           0       0.91      0.78      0.84       105
           1       0.73      0.74      0.73        97
           2       0.74      0.84      0.78        98

    accuracy                           0.79       300
   macro avg       0.79      0.79      0.79       300
weighted avg       0.80      0.79      0.79       300

confusion matrix: 
 [[82 17  6]
 [ 2 72 23]
 [ 6 10 82]]


In [16]:
penalty = ["l1", "l2", "elasticnet"]
c_values = [100, 10, 1, 0.1, 0.01]
solver = ["newton-cg", "lbfgs", "liblenar", "sag", "saga","newton-cholesky"]

In [17]:
params = dict(penalty = penalty, C = c_values, solver = solver)

In [18]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold

In [19]:
cv = StratifiedKFold()

In [20]:
grid = GridSearchCV(estimator = model, param_grid = params, cv = cv, scoring = "accuracy", n_jobs = -1)

In [21]:
grid.fit(X_train, y_train)

/Users/batuhanbasoda/Desktop/CENG/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/batuhanbasoda/Desktop/CENG/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/batuhanbasoda/Desktop/CENG/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/batuhanbasoda/Desktop/CENG/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/batuhanbasoda/Desktop/CENG/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the 

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblenar', 'sag',
                                    'saga', 'newton-cholesky']},
             scoring='accuracy')

In [22]:
grid.best_params_

{'C': 0.1, 'penalty': 'l2', 'solver': 'newton-cg'}

In [23]:
grid.best_score_

np.float64(0.7942857142857143)

In [24]:
y_pred = grid.predict(X_test)

In [25]:
score = accuracy_score(y_pred, y_test)
print("score: ", score)
print(classification_report(y_pred, y_test))
print("confusion matrix: \n", confusion_matrix(y_pred, y_test))

score:  0.7833333333333333
              precision    recall  f1-score   support

           0       0.78      0.91      0.84        90
           1       0.73      0.73      0.73        97
           2       0.84      0.73      0.78       113

    accuracy                           0.78       300
   macro avg       0.78      0.79      0.78       300
weighted avg       0.79      0.78      0.78       300

confusion matrix: 
 [[82  2  6]
 [16 71 10]
 [ 7 24 82]]


In [26]:
# one vs rest 

In [27]:
from sklearn.multiclass import OneVsOneClassifier, OneVsRestClassifier

In [28]:
onevsonemodel = OneVsOneClassifier(LogisticRegression())

In [29]:
onevsrestmodel = OneVsRestClassifier(LogisticRegression())

In [30]:
onevsonemodel.fit(X_train, y_train)
y_pred = onevsonemodel.predict(X_test)
score = accuracy_score(y_test, y_pred)
print("score: ", score)
print(classification_report(y_test, y_pred))
print("confusion matrix: \n", confusion_matrix(y_test, y_pred))

score:  0.7966666666666666
              precision    recall  f1-score   support

           0       0.92      0.80      0.86       105
           1       0.76      0.74      0.75        97
           2       0.73      0.85      0.78        98

    accuracy                           0.80       300
   macro avg       0.80      0.80      0.80       300
weighted avg       0.81      0.80      0.80       300

confusion matrix: 
 [[84 12  9]
 [ 3 72 22]
 [ 4 11 83]]


In [31]:
onevsrestmodel.fit(X_train, y_train)
y_pred = onevsrestmodel.predict(X_test)
score = accuracy_score(y_test, y_pred)
print("score: ", score)
print(classification_report(y_test, y_pred))
print("confusion matrix: \n", confusion_matrix(y_test, y_pred))

score:  0.7833333333333333
              precision    recall  f1-score   support

           0       0.91      0.79      0.85       105
           1       0.73      0.71      0.72        97
           2       0.72      0.85      0.78        98

    accuracy                           0.78       300
   macro avg       0.79      0.78      0.78       300
weighted avg       0.79      0.78      0.78       300

confusion matrix: 
 [[83 16  6]
 [ 2 69 26]
 [ 6  9 83]]


Exception ignored in: <function ResourceTracker.__del__ at 0x105439080>
Traceback (most recent call last):
  File "/Users/batuhanbasoda/Desktop/CENG/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/Users/batuhanbasoda/Desktop/CENG/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/Users/batuhanbasoda/Desktop/CENG/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x1067d5080>
Traceback (most recent call last):
  File "/Users/batuhanbasoda/Desktop/CENG/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/Users/batuhanbasoda/Desktop/CENG/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/Users/batuhanbasoda/Desktop/CENG/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 