In [1]:
import numpy as np 

In [2]:
my_list = [10,20,30,40]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([10, 20, 30, 40])

In [6]:
myNumpyArray = np.array(my_list)

In [7]:
myNumpyArray.max()

np.int64(40)

In [8]:
type(myNumpyArray)

numpy.ndarray

In [9]:
myNumpyArray.min()

np.int64(10)

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.random.random(5)

array([0.13342495, 0.19587644, 0.66739672, 0.78594251, 0.19832565])

In [12]:
myList1 = [1,2]

In [13]:
myList2 = [2,3]

In [14]:
myNumpyArray1 = np.array(myList1)

In [15]:
myNumpyArray2 = np.array(myList2)

In [16]:
myNumpyArray1 + myNumpyArray2

array([3, 5])

In [17]:
# valid for *, -, / 

In [18]:
myNumpyArray1.sum()

np.int64(3)

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np_array = np.arange(0,10)

In [21]:
np_array[0]

np.int64(0)

In [22]:
np_array[-1]

np.int64(9)

In [23]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
np.random.randn(4,4)

array([[-1.04054142, -0.86090198,  0.28637268,  1.20938015],
       [ 1.17406557,  1.037879  ,  1.28372383,  1.38446162],
       [-0.15771193, -0.71139824,  0.86938199, -0.16402442],
       [ 0.3197882 , -1.28125788, -0.06024085, -0.97825894]])

In [25]:
np.random.randint(1,300,5)

array([ 95, 211, 165,  85, 178])

In [27]:
array1 = np.random.random((3,2))

In [28]:
array1

array([[0.52222054, 0.09776395],
       [0.52206444, 0.81582589],
       [0.38894574, 0.38583962]])

In [29]:
array1[1][0]

np.float64(0.5220644430050898)

In [31]:
array2 = np.array([[3,2], [15,20]])

In [32]:
array2

array([[ 3,  2],
       [15, 20]])

In [33]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
first_array = np.array([[15,20], [30,40]])

In [36]:
second_array = np.array([[3,4], [5,6]])

In [37]:
first_array + second_array


array([[18, 24],
       [35, 46]])

In [38]:
third_array = np.array([[50,60]])

In [39]:
first_array + third_array 

array([[ 65,  80],
       [ 80, 100]])

In [41]:
first_array

array([[15, 20],
       [30, 40]])

In [42]:
third_array = np.array([[10], [20]])

In [44]:
third_array

array([[10],
       [20]])

In [45]:
first_array + third_array 

array([[25, 30],
       [50, 60]])

In [46]:
first_array 

array([[15, 20],
       [30, 40]])

In [47]:
second_array 

array([[3, 4],
       [5, 6]])

In [48]:
first_array * second_array 

array([[ 45,  80],
       [150, 240]])

In [49]:
#dot product

In [50]:
first_matrix = np.array([[10,20,30]])

In [51]:
second_matrix = np.array([[2,3], [2,3], [2,3]])

In [52]:
first_matrix

array([[10, 20, 30]])

In [53]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [54]:
result_matrix = first_matrix.dot(second_matrix)

In [55]:
result_matrix

array([[120, 180]])

In [56]:
result_matrix.shape

(1, 2)