In [1]:
import numpy as np 

In [2]:
new_array = np.random.randint(1,100,20)

In [3]:
new_array

array([89, 89, 78, 21, 82, 28,  1,  8, 85, 32,  7, 14, 91, 32, 32, 59, 81,
       65, 61,  4])

In [4]:
new_array > 25 

array([ True,  True,  True, False,  True,  True, False, False,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True, False])

In [5]:
new_array[new_array>2]

array([89, 89, 78, 21, 82, 28,  8, 85, 32,  7, 14, 91, 32, 32, 59, 81, 65,
       61,  4])

In [6]:
new_array[new_array>25]

array([89, 89, 78, 82, 28, 85, 32, 91, 32, 32, 59, 81, 65, 61])

In [7]:
matrix_array = np.array([[10,20], [20,30], [30,40]]) 

In [8]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [9]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [10]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [11]:
random_array = np.random.random((6,1))

In [12]:
random_array

array([[0.54550548],
       [0.3153564 ],
       [0.41788221],
       [0.4969521 ],
       [0.0851708 ],
       [0.41817108]])

In [13]:
random_array.reshape(2,3)

array([[0.54550548, 0.3153564 , 0.41788221],
       [0.4969521 , 0.0851708 , 0.41817108]])

In [14]:
random_array.reshape(3,2)

array([[0.54550548, 0.3153564 ],
       [0.41788221, 0.4969521 ],
       [0.0851708 , 0.41817108]])

In [15]:
# z-score

In [16]:
data = np.array([10,12,13,15,18,25,100,105])

In [17]:
#outlier

In [18]:
mean = np.mean(data)

In [19]:
mean

np.float64(37.25)

In [20]:
std = np.std(data)

In [21]:
std

np.float64(37.9333296719389)

In [22]:
z_scores = (data - mean) / std

In [23]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [24]:
data[z_scores>1]

array([100, 105])

In [25]:
# math equations

In [26]:
#coefficients

In [27]:
A = np.array([[2,3], [5,7]])

In [28]:
#constants

In [31]:
b = np.array([8,19])

In [32]:
solution = np.linalg.solve(A,b)

In [33]:
solution

array([1., 2.])